spring:
  application:
   name: api

  datasource:
    url: jdbc:postgresql://${CONTEST_API_DB_HOST}:${CONTEST_API_DB_PORT}/${CONTEST_API_DB_NAME}
    username: ${CONTEST_API_DB_USER}
    password: ${CONTEST_API_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${CONTEST_API_MAIL_HOST}
    port: ${CONTEST_API_MAIL_PORT}
    username: ${CONTEST_API_MAIL_USERNAME}
    password: ${CONTEST_API_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${CONTEST_API_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${CONTEST_API_MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${CONTEST_API_MAIL_SMTP_STARTTLS_REQUIRED:true}
          from: ${CONTEST_API_MAIL_USERNAME}
          connectiontimeout: ${CONTEST_API_MAIL_CONNECTION_TIMEOUT:5000}
          timeout: ${CONTEST_API_MAIL_TIMEOUT:5000}
          writetimeout: ${CONTEST_API_MAIL_WRITE_TIMEOUT:5000}
        debug: ${CONTEST_API_MAIL_DEBUG:false}

server:
  port: 8080

jwt:
  SECRET_KEY: ${CONTEST_API_JWT_SECRET}
  EXPIRATION_TIME: ${CONTEST_API_JWT_EXPIRATION:3600000}

# Configuración personalizada de la aplicación
app:
  base-url: ${CONTEST_API_BASE_URL:http://localhost:8080}
